version: "3"

services:
  seq:
    image: datalust/seq:preview
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    expose:
      - 5341

  redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - 6379
        
  activemq:
    image: vromero/activemq-artemis
    ports:
      - "8161:8161"
      - "61616:61616"
    expose:
      - 61616
      - 8161