name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7

    - name: Display SemVer
      run: |
        echo "SemVer: $GITVERSION_SEMVER"
      
    - name: Run the Cake script
      uses: cake-build/cake-action@v1
      with:
        script-path: build.cake
        target: CI
        
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      seq:
        image: datalust/seq:latest
        ports:
          - 5341:80
        env:
          ACCEPT_EULA: Y
