name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.x

    - name: Run the Cake script
      uses: cake-build/cake-action@v3
      with:
        script-path: build.cake
        target: ci
        arguments: |
          buildNumber: ${{ github.run_number }}

    - name: Collect Package Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: ./dist_package/Nimbus.*.nupkg

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        trx_files: ./dist_package/**/*.trx
