name: CI

on:
  push:
    branches: [ main, develop, build-workflow ]
  pull_request:
    branches: [ main, develop, build-workflow ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          5.0.x
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7

    - name: Display SemVer
      run: |
        echo "SemVer: $GITVERSION_SEMVER"
      
    - name: Run the Cake script
      uses: cake-build/cake-action@v1
      with:
        script-path: build.cake
        target: Fastci

    - name: Collect Package Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nuget-packages
        path: ./dist_package/Nimbus.*.nupkg

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: ./dist_packages/UnitTests/*.xml        
        
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      seq:
        image: datalust/seq:latest
        ports:
          - 5341:80
        env:
          ACCEPT_EULA: Y
